#!/bin/sh
interface=$1
speed_set=$(nmcli con show eth0 | grep speed | awk '{print $2}')
duplex_set=$(nmcli con show eth0 | grep duplex | awk '{print $2}')

if [ "${speed_set}" != 100 ] || [ "${duplex_set}" != "full" ]
then
	echo "dispatcher: nmcli eth0 modifiying.." > /dev/kmsg
	nmcli connection modify eth0 802-3-ethernet.auto-negotiate no 802-3-ethernet.speed 100 802-3-ethernet.duplex full
fi

echo "dispatcher: autoneg turnoff using dispatcher - ${interface}" > /dev/kmsg
ethtool -s eth0 autoneg off speed 100 duplex full
